version: '3.8'

services:
  bill-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/billtracker
      SPRING_DATASOURCE_USERNAME: tracker
      SPRING_DATASOURCE_PASSWORD: trackerpass
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-bill-db
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: trackerpass
      POSTGRES_DB: billtracker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: